# ZARF_REGISTRY is used here to avoid yolo mode and pointing to localhost without mutating the deployment with zarf, this pattern is required when deploying into kube-system w/ zarf
image:
  repository: "###ZARF_REGISTRY###/autoscaling/cluster-autoscaler"
  # renovate datasource=docker depName=registry.k8s.io/autoscaling/cluster-autoscaler
  tag: v1.32.0
  pullPolicy: IfNotPresent
  pullSecrets:
    - private-registry
