image:
  repository: "###ZARF_REGISTRY###/###ZARF_VAR_IMAGE_REGISTRY_PATH###"
  tag: "###ZARF_VAR_IMAGE_VERSION###"
  pullPolicy: IfNotPresent
  pullSecrets:
    - private-registry

autoDiscovery:
  clusterName: "###ZARF_VAR_CLUSTER_NAME###"
  enabled: true

awsRegion: "###ZARF_VAR_CLUSTER_AWS_REGION###"

rbac:
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "###ZARF_VAR_IAM_ROLE_ARN###"
    name: "###ZARF_VAR_SERVICE_ACCOUNT###"
