package:
  create:
    output: ../../build/registry1
    flavor: registry1
    set:
      package_tag_suffix: ""
      package_name: aws-node-termination-handler
      namespace: aws-node-termination-handler
      chart_repo: oci://public.ecr.aws/aws-ec2/helm/aws-node-termination-handler
      # renovate datasource=docker depName=public.ecr.aws/aws-ec2/helm/aws-node-termination-handler
      chart_version: 0.24.1
      image_registry_repo: registry1.dso.mil
      image_registry_path: ironbank/opensource/aws/aws-node-termination-handler
      # renovate datasource=docker depName=registry1.dso.mil/ironbank/opensource/aws/aws-node-termination-handler
      image_version: v1.13.3
      values_file: values/values.yaml
      overrides_file: values/overrides.yaml

  deploy:
    set:
      cluster_name: "test"
      iam_role_arn: "arn:aws:iam::123456789012:role/test"
      service_account: "test"
      sqs_queue_url: "https://sqs.us-east-2.amazonaws.com/123456789012/test"
      cluster_aws_region: "us-east-2"
