package:
  create:
    output: ../../build/upstream
    flavor: upstream
    set:
      package_tag_suffix: ""
      # renovate datasource=docker depName=public.ecr.aws/aws-ec2/helm/aws-node-termination-handler
      chart_version: 0.27.1
      # renovate datasource=docker depName=public.ecr.aws/aws-ec2/aws-node-termination-handler
      image_version: v1.25.1

  deploy:
    set:
      cluster_name: "test"
      iam_role_arn: "arn:aws:iam::123456789012:role/test"
      service_account: "test"
      sqs_queue_url: "https://sqs.us-east-2.amazonaws.com/123456789012/test"
      cluster_aws_region: "us-east-2"
