variables:
  - name: VERSION
    description: "The version of the package to deploy"
    # x-release-please-start-version
    default: "0.0.1"
    # x-release-please-end-version

tasks:
  - name: deploy-all-packages
    actions:
      - description: "Deploy the uds"
        cmd: |
          uds deploy
