includes:
  - vars: ./tasks/vars.yaml
  - infra: ./tasks/infra/main.yaml

variables:
  - name: K3D_CLUSTER_NAME
    description: "The name of the cluster to create"
    default: "uds"
  - name: K3D_IMAGE
    description: "K3d image to use"
    type: file
    default: rancher/k3s:v1.21.2-k3s1
  - name: UDS_DEPLOY_DIR
    description: "The directory to deploy from"
    default: "/tmp/uds"

tasks:
  # - name: k3d-setup-cluster
  #   actions:
  #     - description: "Create the K3d cluster"
  #       # renovate: datasource=github-tags depName=defenseunicorns/uds-k3d versioning=semver
  #       cmd: |
  #         k3d cluster create \
  #         --k3s-arg "--disable=traefik@server:*" \
  #         --k3s-arg "--disable=servicelb@server:*" \
  #         --image ${K3D_IMAGE} \
  #         ${K3D_CLUSTER_NAME}
  - name: aws-infra-up
    description: "Main entrypoint for setting up aws IaC"
    actions:
      - task: infra:aws-infra-up
