package:
  create:
    output: ../../build/upstream
    flavor: upstream
    set:
      package_tag_suffix: ""
      # renovate datasource=helm depName=metrics-server registryUrl=https://kubernetes-sigs.github.io/metrics-server
      chart_version: 3.12.2
      # renovate datasource=docker depName=registry.k8s.io/metrics-server/metrics-server
      image_version: v0.7.2
