package:
  create:
    output: ../../build
    set:
      package_tag_suffix: -registry1
      package_name: metrics-server
      namespace: kube-system
      chart_repo: https://kubernetes-sigs.github.io/metrics-server/
      # renovate datasource=helm depName=metrics-server registryUrl=https://kubernetes-sigs.github.io/metrics-server
      chart_version: 3.12.1
      image_registry_repo: registry1.dso.mil
      image_registry_path: ironbank/opensource/kubernetes-sigs/metrics-server
      # renovate datasource=docker depName=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/metrics-server
      image_version: v0.7.1
      values_file: values/values.yaml
      overrides_file: values/overrides.yaml
