package:
  create:
    output: ../../build
    set:
      package_version: 0.0.1
      package_name: metrics-server
      namespace: kube-system
      chart_repo: https://kubernetes-sigs.github.io/metrics-server/
      chart_version: 3.10.0
      image_registry_repo: registry1.dso.mil
      image_registry_path: ironbank/opensource/kubernetes-sigs/metrics-server
      image_version: v0.6.3
      values_file: values/values.yaml
      overrides_file: values/overrides.yaml
