package:
  create:
    output: ../../build/registry1
    flavor: registry1
    set:
      package_tag_suffix: ""
      # renovate datasource=helm depName=metrics-server registryUrl=https://kubernetes-sigs.github.io/metrics-server
      chart_version: 3.12.2
      # renovate datasource=docker depName=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/metrics-server
      image_version: v0.8.0
