package:
  create:
    output: ../../build/registry1
    flavor: registry1
    set:
      package_tag_suffix: ""
      # renovate datasource=helm depName=cluster-autoscaler registryUrl=https://kubernetes.github.io/autoscaler
      chart_version: 9.46.3
      # renovate datasource=docker depName=registry1.dso.mil/ironbank/opensource/kubernetes/autoscaler
      image_version: v1.32.1

  deploy:
    set:
      cluster_name: "test"
      iam_role_arn: "arn:aws:iam::123456789012:role/test"
      service_account: "test"
      cluster_aws_region: "us-east-2"
