package:
  create:
    output: ../../build/upstream
    set:
      package_tag_suffix: ""
      package_name: cluster-autoscaler
      namespace: kube-system
      chart_repo: https://kubernetes.github.io/autoscaler
      # renovate datasource=helm depName=cluster-autoscaler registryUrl=https://kubernetes.github.io/autoscaler
      chart_version: 9.50.1
      image_registry_repo: registry.k8s.io
      image_registry_path: autoscaling/cluster-autoscaler
      # renovate datasource=docker depName=registry.k8s.io/autoscaling/cluster-autoscaler
      image_version: v1.33.0
      values_file: values/values.yaml
      overrides_file: values/overrides.yaml

  deploy:
    set:
      cluster_name: "test"
      iam_role_arn: "arn:aws:iam::123456789012:role/test"
      service_account: "test"
      cluster_aws_region: "us-east-2"
