package:
  create:
    output: ../../build/upstream
    flavor: upstream
    set:
      package_tag_suffix: ""
      # renovate datasource=helm depName=cluster-autoscaler registryUrl=https://kubernetes.github.io/autoscaler
      chart_version: 9.51.0
      # renovate datasource=docker depName=registry.k8s.io/autoscaling/cluster-autoscaler
      image_version: v1.34.1

  deploy:
    set:
      cluster_name: "test"
      iam_role_arn: "arn:aws:iam::123456789012:role/test"
      service_account: "test"
      cluster_aws_region: "us-east-2"
