package:
  create:
    output: ../../build
    set:
      # x-release-please-start-version
      package_version: 0.0.1
      # x-release-please-end
      package_name: cluster-autoscaler
      namespace: kube-system
      chart_repo: https://kubernetes.github.io/autoscaler
      chart_version: 9.29.1
      image_registry_repo: registry1.dso.mil
      image_registry_path: ironbank/opensource/kubernetes/autoscaler
      image_version: v1.27.3
      values_file: values/values.yaml
      overrides_file: values/overrides.yaml

  deploy:
    set:
      cluster_name: "test"
      iam_role_arn: "arn:aws:iam::123456789012:role/test"
      service_account: "test"
