package:
  create:
    output: ../../build/registry1
    flavor: registry1
    set:
      package_tag_suffix: ""
      # renovate datasource=helm depName=aws-load-balancer-controller registryUrl=https://aws.github.io/eks-charts
      chart_version: 1.14.1
      # renovate datasource=docker depName=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/aws-load-balancer-controller
      image_version: v2.14.1

  deploy:
    set:
      cluster_name: "test"
      iam_role_arn: "arn:aws:iam::123456789012:role/test"
      service_account: "test"
      cluster_aws_region: "us-east-2"
