apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
reclaimPolicy: "###ZARF_VAR_RECLAIM_POLICY###"
allowVolumeExpansion: ###ZARF_VAR_ALLOW_VOLUME_EXPANSION###
volumeBindingMode: "###ZARF_VAR_VOLUME_BINDING_MODE###"
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: gp3
  encrypted: "true"
  ###ZARF_VAR_EBS_EXTRA_PARAMETERS###
