package:
  create:
    output: ../../build
    set:
      package_version: 0.0.1
      package_name: external-secrets
      package_tag_suffix: -registry1
      namespace: external-secrets
      chart_repo: https://charts.external-secrets.io
      # renovate datasource=helm depName=external-secrets registryUrl=https://charts.external-secrets.io
      chart_version: 0.9.17
      image_registry_repo: registry1.dso.mil
      image_registry_path: ironbank/opensource/external-secrets/external-secrets
      # renovate datasource=docker depName=registry1.dso.mil/ironbank/opensource/external-secrets/external-secrets
      image_version: v0.9.16
      values_file: values/values.yaml
      overrides_file: values/overrides.yaml
