package:
  create:
    output: ../../build/registry1
    flavor: registry1
    set:
      package_name: external-secrets
      package_tag_suffix: ""
      namespace: external-secrets
      chart_repo: https://charts.external-secrets.io
      # renovate datasource=helm depName=external-secrets registryUrl=https://charts.external-secrets.io
      chart_version: 0.19.2
      image_registry_repo: registry1.dso.mil
      image_registry_path: ironbank/opensource/external-secrets/external-secrets
      # renovate datasource=docker depName=registry1.dso.mil/ironbank/opensource/external-secrets/external-secrets
      image_version: v0.19.2
      values_file: values/values.yaml
      overrides_file: values/overrides.yaml
