# https://github.com/aws/karpenter-provider-aws/tree/main/charts/karpenter
# https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/values.yaml
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "###ZARF_VAR_IAM_ROLE_ARN###"

settings:
  clusterName: "###ZARF_VAR_CLUSTER_NAME###"
  interruptionQueue: "###ZARF_VAR_CLUSTER_NAME###"

controller:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi

replicas: 1



#   name: "###ZARF_VAR_SERVICE_ACCOUNT###"
#   annotations:
#     eks.amazonaws.com/role-arn: "###ZARF_VAR_IAM_ROLE_ARN###"

# region: "###ZARF_VAR_CLUSTER_AWS_REGION###"

# clusterName: "###ZARF_VAR_CLUSTER_NAME###"


# helm upgrade --install --namespace karpenter --create-namespace \
#   karpenter oci://public.ecr.aws/karpenter/karpenter \
#   --version 1.0.0 \
#   --set "serviceAccount.annotations.eks\.amazonaws\.com/role-arn=${KARPENTER_IAM_ROLE_ARN}" \
#   --set settings.clusterName=${CLUSTER_NAME} \
#   --set settings.interruptionQueue=${CLUSTER_NAME} \
#   --wait