package:
  create:
    set:
      package_version: 0.0.1
      package_name: metrics-server
      namespace: kube-system
      chart_repo: https://kubernetes-sigs.github.io/metrics-server/
      chart_version: 3.10.0
      image_repo: registry1.dso.mil/ironbank/opensource/kubernetes-sigs/metrics-server
      image_version: v0.6.3
