serviceAccount:
  name: "###ZARF_VAR_SERVICE_ACCOUNT###"
  annotations:
    eks.amazonaws.com/role-arn: "###ZARF_VAR_IAM_ROLE_ARN###"

awsRegion: "###ZARF_VAR_CLUSTER_AWS_REGION###"

queueURL: "###ZARF_VAR_SQS_QUEUE_URL###"

enableSqsTerminationDraining: true
