image:
  repository: "###ZARF_REGISTRY###/###ZARF_VAR_IMAGE_REGISTRY_PATH###"
  tag: "###ZARF_VAR_IMAGE_VERSION###"
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: private-registry

serviceAccount:
  name: "###ZARF_VAR_SERVICE_ACCOUNT###"
  annotations:
    eks.amazonaws.com/role-arn: "###ZARF_VAR_IAM_ROLE_ARN###"

awsRegion: "###ZARF_VAR_CLUSTER_AWS_REGION###"

queueURL: "###ZARF_VAR_SQS_QUEUE_URL###"

enableSqsTerminationDraining: true
