# ZARF_REGISTRY is used here to avoid yolo mode and pointing to localhost without mutating the deployment with zarf
image:
  repository: "###ZARF_REGISTRY###/ironbank/kubernetes-sigs/aws-load-balancer-controller"
  tag: v2.8.0
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: private-registry
