# ZARF_REGISTRY is used here to avoid yolo mode and pointing to localhost without mutating the deployment with zarf, this pattern is required when deploying into kube-system w/ zarf
image:
  repository: "###ZARF_REGISTRY###/ironbank/kubernetes-sigs/aws-load-balancer-controller"
  # renovate datasource=docker depName=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/aws-load-balancer-controller
  tag: v2.13.4
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: private-registry
