# ZARF_REGISTRY is used here to avoid yolo mode and pointing to localhost without mutating the deployment with zarf, this pattern is required when deploying into kube-system w/ zarf
image:
  repository: "###ZARF_REGISTRY###/eks/aws-load-balancer-controller"
  # renovate datasource=docker depName=public.ecr.aws/eks/aws-load-balancer-controller
  tag: v2.9.0
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: private-registry
