serviceAccount:
  name: "###ZARF_VAR_SERVICE_ACCOUNT###"
  annotations:
    eks.amazonaws.com/role-arn: "###ZARF_VAR_IAM_ROLE_ARN###"

region: "###ZARF_VAR_CLUSTER_AWS_REGION###"

clusterName: "###ZARF_VAR_CLUSTER_NAME###"
