# triggers on merge_group and pull_request events
# only use this if merge queue is enabled, otherwise stick to test-command for e2e testing

name: pr-merge-group
on:
  merge_group:
    types: [checks_requested]
  pull_request:
  push:

defaults:
  run:
    shell: bash -eo pipefail {0}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run Build and Publish Target
        run: make zarf-build-and-publish-all