name: publish-uds-bundles-and-zarf-packages

on:
  workflow_dispatch:

jobs:
  publish-uds-bundles-and-zarf-packages:
    runs-on: ubuntu-latest
    name: publish packages
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: environment setup
        uses: defenseunicorns/uds-core/.github/actions/setup@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          ib_user: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          ib_password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}

      - name: Login to GHCR
        run: |
          uds run registry-login \
            --set REGISTRY=ghcr.io \
            --set REGISTRY_USERNAME=dummy \
            --set REGISTRY_PASSWORD=${{ secrets.GITHUB_TOKEN }} \
            --set REGISTRY_RETRY_INTERVAL=90

      - name: Login to registry1
        run: |
          uds run registry-login \
            --set REGISTRY=registry1.dso.mil \
            --set REGISTRY_USERNAME=${{ secrets.IRON_BANK_ROBOT_USERNAME }} \
            --set REGISTRY_PASSWORD=${{ secrets.IRON_BANK_ROBOT_PASSWORD }} \
            --set REGISTRY_RETRY_INTERVAL=90

      - name: publish Zarf Packages
        run: uds run publish-packages

      - name: publish UDS Bundles
        run: uds run publish-bundles

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-core/.github/actions/save-logs@main
        with:
          suffix: "-eks-addons"
