name: release-packages

on:
  workflow_dispatch:
  # trigger on push to main branch when a yaml file under packages directory is changed
  push:
    branches:
      - "main"
    paths:
      - "packages/**/*.y*ml"

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.zarf_all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45
        with:
          matrix: true
          files_yaml: |
            zarf:
              - '**.{yaml,yml}'
              - '**/*.{yaml,yml}'
          path: packages/ # only look in the packages directory
          dir_names: true # just give the directory names
          dir_names_max_depth: 1 # only look at the first level of directories
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.zarf_all_changed_files }}'

  publish-packages:
    name: Run Matrix Job
    runs-on: ubuntu-latest
    needs: [changed-files]
    if: ${{ needs.changed-files.outputs.matrix != '[]' }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        zarf-package: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 10
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Environment setup
        uses: ./.github/actions/setup
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: publish ${{ matrix.zarf-package }} zarf package
        run: |
          ZARF_PACKAGE_NAME=${{ matrix.zarf-package }} uds run create-and-publish-single-zarf-package-with-all-architectures

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-core/.github/actions/save-logs@main
        with:
          suffix: ${{ matrix.zarf-package }}-${{ github.run_id }}-${{ github.run_attempt }}
