name: release-packages

on:
  # manual, idk
  workflow_dispatch:
  # Detect changes to files made since the last pushed commit.
  push:
    branches:
      - refactor/change-release-patterns
  # Detect changes to all files in a Pull request relative to the target branch or since the last pushed commit.
  pull_request:
    branches:
      - main

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.zarf_all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          matrix: true
          files_yaml: |
            zarf:
              - 'packages/**zarf*.yaml'
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.zarf_all_changed_files }}'

  matrix-job:
    name: Run Matrix Job
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix:
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          echo ${{ matrix.files }}
